server:
  port: 8090
spring:
  application:
    name: microservice-login
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logindb
    username: sofia
    password: Lol1P0psy13*
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    config:
      enabled: false
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 40  # Tiempo entre cada latido
    lease-expiration-duration-in-seconds: 60  # Tiempo de expiración si el microservicio no responde
  client:
    service-url:
      dafaultZone: http://localhost:8761/eureka
      fetch-registry: true  # Permite al cliente obtener registros
      register-with-eureka: true  # Registra al cliente con Eureka









