server:
  port: 8090
spring:
  application:
    name:
      login
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logindb
    username: root
    password: Juanes1330*
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30  # Tiempo entre cada latido
    lease-expiration-duration-in-seconds: 90  # Tiempo de expiración si el microservicio no responde
  client:
    service-url:
      dafaultZone: http://localhost:8761/eureka
      fetch-registry: true  # Permite al cliente obtener registros
      register-with-eureka: true  # Registra al cliente con Eureka






