server:
  port: 6090

spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  application:
    name: pagos
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 1   # Número de hilos concurrentes para el consumidor
        max-concurrency: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pagosdb
    username: root
    password: Juanes1330*
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
rabbitmq:
  queue:
    name: pagos_orden
  exchange:
    name: pagos_orden_exchange
  routing:
    key: pagos_orden_key