server:
  port: 7070
spring:
  application:
    name:
      microservice-ordenes
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ordenesdb
    username: sofia
    password: Lo1P0psy13*
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30  # Tiempo entre cada latido
    lease-expiration-duration-in-seconds: 90  # Tiempo de expiración si el microservicio no responde
  client:
    service-url:
      dafaultZone: http://localhost:8761/eureka
      fetch-registry: true  # Permite al cliente obtener registros
      register-with-eureka: true  # Registra al cliente con Eureka





