server:
  port: 7070

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: Ordenes
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ordenesdb
    username: root
    password: Juanes1330*

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30  # Tiempo entre cada latido
    lease-expiration-duration-in-seconds: 90  # Tiempo de expiración si el microservicio no responde
  client:
    service-url:
      dafaultZone: http://localhost:8761/eureka
      fetch-registry: true  # Permite al cliente obtener registros
      register-with-eureka: true  # Registra al cliente con Eureka

rabbitmq:
  queue:
    name: orden
  exchange:
    name: orden_json
  routing:
    key: orden_routing_key
    json:
      key: orden_json_key