server:
  port: 8080
spring:
  application:
    name: gateaway
  config:
      import: optional:configserver:http//localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: login
          uri: http://localhost:8090
          predicates:
            - Path=/api/login/**
        - id: inventario
          uri: http://localhost:9090
          predicates:
            - Path=/api/inventario/**
          filters:
            - RewritePath=/api/inventario/(?<segment>.*), /api/products/$\{segment}
        - id: ordenes
          uri: http://localhost:7070
          predicates:
            - Path=/api/ordenes/**
          filters:
            - RewritePath=/api/ordenes/(?<segment>.*), /api/orden/$\{segment}
        - id: pagos
          uri: http://localhost:6090
          predicates:
            - Path=/api/pagos/**
          filters:
            - RewritePath=/api/pagos/(?<segment>.*), /api/pago/$\{segment}




