server:
  port: 9090

spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  application:
    name: inventario
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventariodb
    username: root
    password: Juanes1330*
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka





