server:
  port: 9090

spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: inventario
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventariodb
    username: root
    password: Juanes1330*
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchange:
    name: orden_json
  queue:
    inventario: inventario_orden
  routing:
    inventario:
      key: inventario_orden_key




